config/routes.rb
Forms::Plugin.routes.draw do
  extend Wheelhouse::RouteExtensions
  
  resources :forms do
    resources :submissions
  end
end

app/models/forms/field_collection.rb
class Forms::FieldCollection < MongoModel::Collection[Forms::Fields::Field]
  include ActionView::Helpers::OutputSafetyHelper
  
  def to_html(template)
    safe_join(map { |field| field.to_html(template) })
  end
  
  def map_with_index
    result = []
    each_with_index { |item, index| result[index] = yield(item, index) }
    result
  end
  
  def self.cast(collection)
    case collection
    when Hash
      sorted_attrs = collection.sort { |(a, _), (b, _)| a.to_i <=> b.to_i }.map { |_, attrs| attrs }
      super(sorted_attrs)
    else
      super
    end
  end
end

app/models/forms/fields/checkbox.rb
module Forms::Fields
  class Checkbox < Field
    property :label, String
    property :required, Boolean, :default => false

    def to_html(template)
      super do
        label_tag { check_box_tag(name, "1", false, html_options) + " " + label }
      end
    end

    def reference
      label
    end
  end
end

app/models/forms/fields/checkboxes.rb
module Forms::Fields
  class Checkboxes < Field
    include LabelledField
    include OptionedField
  
    property :label, String
    property :required, Boolean, :default => false
  
    def to_html(template)
      super { content_tag(:ul, safe_join(options.map { |o| content_tag(:li, checkbox(o)) })) }
    end
  
  protected
    def checkbox(option)
      content_tag(:label, :class => "option") { check_box_tag("#{name}[]", option, false, :id => nil) + " " + option }
    end
  end
end

app/models/forms/fields/content_field.rb
module Forms::Fields
  class ContentField < Field
    property :content, Translated[ActionView::OutputBuffer]
  
    def to_html(template)
      super { content.to_s }
    end
  end
end

app/models/forms/fields/countries_dropdown.rb
module Forms::Fields
  class CountriesDropdown < SelectField
    properties.delete(:options)
  
    property :label, String, :default => "Country"

    def options
      COUNTRIES
    end

    COUNTRIES = ["Afghanistan", "Aland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola",
      "Anguilla", "Antarctica", "Antigua And Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria",
      "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin",
      "Bermuda", "Bhutan", "Bolivia", "Bosnia and Herzegowina", "Botswana", "Bouvet Island", "Brazil",
      "British Indian Ocean Territory", "Brunei Darussalam", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia",
      "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China",
      "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo",
      "Congo, the Democratic Republic of the", "Cook Islands", "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba",
      "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt",
      "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands (Malvinas)",
      "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia",
      "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea",
      "Guinea-Bissau", "Guyana", "Haiti", "Heard and McDonald Islands", "Holy See (Vatican City State)",
      "Honduras", "Hong Kong", "Hungary", "Iceland", "India", "Indonesia", "Iran, Islamic Republic of", "Iraq",
      "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya",
      "Kiribati", "Korea, Democratic People's Republic of", "Korea, Republic of", "Kuwait", "Kyrgyzstan",
      "Lao People's Democratic Republic", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libyan Arab Jamahiriya",
      "Liechtenstein", "Lithuania", "Luxembourg", "Macao", "Macedonia, The Former Yugoslav Republic Of",
      "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique",
      "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia, Federated States of", "Moldova, Republic of",
      "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru",
      "Nepal", "Netherlands", "Netherlands Antilles", "New Caledonia", "New Zealand", "Nicaragua", "Niger",
      "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "Norway", "Oman", "Pakistan", "Palau",
      "Palestinian Territory, Occupied", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines",
      "Pitcairn", "Poland", "Portugal", "Puerto Rico", "Qatar", "Reunion", "Romania", "Russian Federation",
      "Rwanda", "Saint Barthelemy", "Saint Helena", "Saint Kitts and Nevis", "Saint Lucia",
      "Saint Pierre and Miquelon", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
      "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore",
      "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa",
      "South Georgia and the South Sandwich Islands", "Spain", "Sri Lanka", "Sudan", "Suriname",
      "Svalbard and Jan Mayen", "Swaziland", "Sweden", "Switzerland", "Syrian Arab Republic",
      "Taiwan, Province of China", "Tajikistan", "Tanzania, United Republic of", "Thailand", "Timor-Leste",
      "Togo", "Tokelau", "Tonga", "Trinidad and Tobago", "Tunisia", "Turkey", "Turkmenistan",
      "Turks and Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom",
      "United States", "United States Minor Outlying Islands", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela",
      "Viet Nam", "Virgin Islands, British", "Virgin Islands, U.S.", "Wallis and Futuna", "Western Sahara",
      "Yemen", "Zambia", "Zimbabwe"]
  end
end

app/models/forms/fields/custom_field.rb
module Forms::Fields
  class CustomField < Field
    property :label, String
    property :partial, String

    def to_html(template)
      super { template.render :partial => partial, :locals => { :field => self } }
    end
  
    def reference
      label
    end
  end
end

app/models/forms/fields/field.rb
module Forms::Fields
  class Field < Wheelhouse::EmbeddedResource
    include ActionView::Helpers::FormTagHelper
    include ActionView::Helpers::OutputSafetyHelper
    attr_accessor :output_buffer

    def self.partial
      name.demodulize.underscore
    end

    def self.field_class
      partial.dasherize
    end
    
    def self.cast(attrs)
      case attrs
      when Hash
        type = attrs.delete(:type)
        klass = type ? type.constantize : self
        klass.new(attrs)
      else
        super
      end
    end
    
    delegate :field_class, :to => "self.class"

    def to_html(template)
      content_tag(:div, :class => classes.join(" ")) { yield if block_given? }
    end

    def name
      "submission[#{reference}]"
    end

  protected
    def html_options
      options = {}
      options[:required] = "required" if respond_to?(:required?) && required?
      options
    end
    
    def classes
      ["field"].tap do |classes|
        classes << field_class
        classes << "required" if respond_to?(:required?) && required?
        classes << reference.parameterize if respond_to?(:reference)
      end
    end
  end
end

app/models/forms/fields/field_set.rb
module Forms::Fields
  class FieldSet < Field
    property :legend, String
    property :fields, Forms::FieldCollection

    def to_html(template)
      content_tag(:fieldset, :class => legend? ? legend.parameterize : '') do
        ActiveSupport::SafeBuffer.new.tap do |result|
          result << content_tag(:legend, legend) if legend?
          result << fields.to_html(template)
        end
      end
    end
  end
end

app/models/forms/fields/labelled_field.rb
module Forms::Fields
  module LabelledField
    def to_html(template)
      super do
        result = ActiveSupport::SafeBuffer.new
        result << label_tag(name, label.html_safe) if label?
        result << yield if block_given?
        result
      end
    end

    def reference
      label
    end
  end
end

app/models/forms/fields/optioned_field.rb
module Forms::Fields
  module OptionedField
    extend ActiveSupport::Concern
  
    included do
      property :options, MongoModel::Collection[String]
    end
  
    def options=(options)
      write_attribute(:options, options.reject(&:blank?))
    end

    def options(include_blank = false)
      read_attribute(:options) + (include_blank ? [""] : [])
    end
  end
end

app/models/forms/fields/radio_buttons.rb
module Forms::Fields
  class RadioButtons < Field
    include LabelledField
    include OptionedField
  
    property :label, String
    property :required, Boolean, :default => false
  
    def to_html(template)
      super { content_tag(:ul, safe_join(options.map { |o| content_tag(:li, radio_button(o)) })) }
    end
  
  protected
    def radio_button(option)
      content_tag(:label, :class => "option") { radio_button_tag(name, option, false, :id => nil) + " " + option }
    end
  end
end

app/models/forms/fields/select_field.rb
module Forms::Fields
  class SelectField < Field
    include LabelledField
    include OptionedField
    include ActionView::Helpers::FormOptionsHelper

    property :label, String
    property :required, Boolean, :default => false

    def to_html(template)
      super { select_tag(name, options_for_select(options), html_options) }
    end
  end
end

app/models/forms/fields/states_dropdown.rb
module Forms::Fields
  class StatesDropdown < SelectField
    properties.delete(:options)
  
    property :label, String, :default => "State"
    property :country, String, :required => true

    def options
      STATES[country]
    end

    STATES = {
      "US" => [
          [ "Alabama", "AL" ], 
          [ "Alaska", "AK" ], 
          [ "Arizona", "AZ" ], 
          [ "Arkansas", "AR" ], 
          [ "California", "CA" ], 
          [ "Colorado", "CO" ], 
          [ "Connecticut", "CT" ], 
          [ "Delaware", "DE" ], 
          [ "District Of Columbia", "DC" ], 
          [ "Florida", "FL" ], 
          [ "Georgia", "GA" ], 
          [ "Hawaii", "HI" ], 
          [ "Idaho", "ID" ], 
          [ "Illinois", "IL" ], 
          [ "Indiana", "IN" ], 
          [ "Iowa", "IA" ], 
          [ "Kansas", "KS" ], 
          [ "Kentucky", "KY" ], 
          [ "Louisiana", "LA" ], 
          [ "Maine", "ME" ], 
          [ "Maryland", "MD" ], 
          [ "Massachusetts", "MA" ], 
          [ "Michigan", "MI" ], 
          [ "Minnesota", "MN" ], 
          [ "Mississippi", "MS" ], 
          [ "Missouri", "MO" ], 
          [ "Montana", "MT" ], 
          [ "Nebraska", "NE" ], 
          [ "Nevada", "NV" ], 
          [ "New Hampshire", "NH" ], 
          [ "New Jersey", "NJ" ], 
          [ "New Mexico", "NM" ], 
          [ "New York", "NY" ], 
          [ "North Carolina", "NC" ], 
          [ "North Dakota", "ND" ], 
          [ "Ohio", "OH" ], 
          [ "Oklahoma", "OK" ], 
          [ "Oregon", "OR" ], 
          [ "Pennsylvania", "PA" ], 
          [ "Rhode Island", "RI" ], 
          [ "South Carolina", "SC" ], 
          [ "South Dakota", "SD" ], 
          [ "Tennessee", "TN" ], 
          [ "Texas", "TX" ], 
          [ "Utah", "UT" ], 
          [ "Vermont", "VT" ], 
          [ "Virginia", "VA" ], 
          [ "Washington", "WA" ], 
          [ "West Virginia", "WV" ], 
          [ "Wisconsin", "WI" ], 
          [ "Wyoming", "WY" ]
        ],
    
      "Australia" => [
          [ "Australian Capital Territory", "ACT" ],
          [ "New South Wales", "NSW" ],
          [ "Northern Territory", "NT" ],
          [ "South Australia", "SA" ],
          [ "Tasmania", "TAS" ],
          [ "Victoria", "VIC" ],
          [ "Western Australia", "WA" ],
          [ "Queensland", "QLD" ]
        ]
    }
  end
end

app/models/forms/fields/text_area.rb
module Forms::Fields
  class TextArea < Field
    include LabelledField

    property :label, String
    property :required, Boolean, :default => false

    def to_html(template)
      super { text_area_tag(name, nil, html_options) }
    end
  end
end

app/models/forms/fields/text_field.rb
module Forms::Fields
  class TextField < Field
    include LabelledField

    property :label, String
    property :required, Boolean, :default => false

    def to_html(template)
      super { text_field_tag(name, nil, html_options) }
    end
  end
end

app/models/forms/form.rb
class Forms::Form < Wheelhouse::Resource
  include Wheelhouse::Resource::Node
  include Wheelhouse::Resource::Renderable
  include Wheelhouse::Resource::Addressable
  include Wheelhouse::Resource::Versioned
  include Wheelhouse::Resource::Content
  
  property :title, String, :required => true, :translate => true
  property :fields, FieldCollection, :default => [Forms::Fields::FieldSet.new]
  property :recipients, MongoModel::Collection[String]
  property :subject, String, :default => "Form Submission"
  
  has_many :submissions, :class => "Forms::Submission"
  
  activities :all
  
  icon "wheelhouse-forms/form.png"
  
  include ActionView::Helpers::FormTagHelper
  attr_accessor :output_buffer, :context
  
  def to_s
    render(context)
  end
  
  def render(template)
    form_tag(path) do
      fields.to_html(template) + content_tag(:div, submit_tag(I18n.t("Submit")), :class => "submit")
    end
  end
  
  def submit(params)
    submissions.build(:params => params) do |submission|
      submission.save!
      deliver(submission)
    end
    
    @success = true
  end
  
  def deliver(submission)
    Forms::Mailer.submission(self, submission).deliver unless recipients.empty?
  rescue
    # Mail delivery failed
  end
  
  def success?
    @success
  end
  
  def errors?
    false
  end
  
  def first_content_field
    @first_content_field ||= begin
      result = fields.first
      result = result.fields.first if result.is_a?(Forms::Fields::FieldSet)
      result
    end
  end
  
  def recipients_string
    recipients.join(', ')
  end
  
  def recipients_string=(recipients)
    self.recipients = recipients.split(/,/).map(&:strip)
  end
  
  def handler
    Forms::FormHandler
  end
  
  def protect_against_forgery?
    false
  end
  
  def controller
  end
end

app/models/forms/submission.rb
class Forms::Submission < Wheelhouse::BasicResource
  include Wheelhouse::Resource::AdminPath
  
  property :params, Hash
  timestamps!
  
  belongs_to :form, :class => "Forms::Form"
  
  default_scope order(:created_at.desc)
  
  def value_for(field)
    params[field.label]
  end
  
  def admin_path
    form_submission_path(form_id, id)
  end
  
  def admin_url
    form_submission_url(form, id, :host => form.site.domain)
  end
end

app/controllers/forms/forms_controller.rb
class Forms::FormsController < Wheelhouse::ResourceController
  self.resource_class = Forms::Form
  manage_site_breadcrumb
  
  def version
    resource.revert_to(params[:version].to_i)
    render :edit
  end
end

app/controllers/forms/submissions_controller.rb
class Forms::SubmissionsController < Wheelhouse::ResourceController
  belongs_to :form, :class_name => Forms::Form
  self.resource_class = Forms::Submission
  
  manage_site_breadcrumb
  breadcrumb { [parent.label, parent] }
  
  actions :show, :destroy
  
  respond_to :csv
  
  def index
    respond_with(parent) do |format|
      format.csv { render :text => Forms::Form.to_csv }
    end
  end
end

app/helpers/forms/forms_helper.rb
module Forms::FormsHelper
  def render_fields(fields, prefix)
    fields.map_with_index do |field, index|
      render(:partial => field.class.partial, :object => field, :locals => { :index => index, :prefix => "#{prefix}[#{index}]", :id => "" })
    end.join("\n").html_safe
  end
  
  def field_template(id, klass)
    jquery_template_tag(id) do
      render :partial => klass.partial, :object => klass.new, :locals => { :index => "${index}", :prefix => "${prefix}", :id => "${id}" }
    end
  end
  
  def basic_field(object, options={})
    render :partial => "basic_field",
           :object => object,
           :locals => {
                        :id => options[:id],
                        :prefix => options[:prefix],
                        :index => options[:index],
                        :type => options[:type],
                        :description => options[:description],
                        :icon => options[:icon] || options[:type]
                      }
  end
end

app/views/forms/forms/_basic_field.haml
%div{ :class => type, 'data-index' => index }
  %input{:type => "hidden", :name => "#{prefix}[type]", :value => basic_field.type}
  
  .drag= image_tag "wheelhouse-forms/#{icon}.png", :alt => description, :title => description
  
  %input{:type => "text", :name => "#{prefix}[label]", :title => "#{description} Label", :placeholder => "#{description} Label", :value => basic_field.label}
  
  %label.required
    %input{:type => "checkbox", :name => "#{prefix}[required]", :value => "1", :checked => basic_field.required?}
    This field is required
  
  = link_to "Delete", '#', :class => 'delete'

app/views/forms/forms/_checkboxes.haml
.checkboxes{ 'data-index' => index }
  %input{:type => "hidden", :name => "#{prefix}[type]", :value => checkboxes.type}
  
  .drag= image_tag "wheelhouse-forms/checkboxes.png", :alt => "Checkboxes", :title => "Checkboxes"
  
  %input{:type => "text", :name => "#{prefix}[label]", :title => "Checkboxes Label", :placeholder => "Checkboxes Label", :value => checkboxes.label}
  
  %label.required
    %input{:type => "checkbox", :name => "#{prefix}[required]", :value => "1", :checked => checkboxes.required?}
    This field is required
  
  = link_to "Delete", '#', :class => 'delete'
  
  %ul.options
    %li
      %label Options:
      
    - checkboxes.options(true).each do |option|
      %li
        %input{:type => "text", :name => "#{prefix}[options][]", :value => option}

app/views/forms/forms/_content_field.haml
.content-field{ 'data-index' => index }
  %input{:type => "hidden", :name => "#{prefix}[type]", :value => content_field.type}
  
  .drag= image_tag "wheelhouse-forms/content.png", :alt => "Content Field", :title => "Content Field"
  
  %textarea.editor{:name => "#{prefix}[content]", :rows => 5}= content_field.content
  
  = link_to "Delete", '#', :class => 'delete'

app/views/forms/forms/_countries_dropdown.haml
= basic_field(countries_dropdown, :index => index, :prefix => prefix, :id => id, :type => "countries-dropdown", :description => "Countries Dropdown", :icon => "countries")

app/views/forms/forms/_field_set.haml
.field-set{ "data-index" => index }
  %input{:type => "hidden", :name => "#{prefix}[type]", :value => field_set.type}
  
  .drag
  
  %label{:for => "fieldset_#{index}_legend"} Fieldset Legend:
  %input{:id => "fieldset_#{index}_legend", :type => "text", :name => "#{prefix}[legend]", :value => field_set.legend}
  
  %span.note (leave blank for none)

  .fields{ "data-prefix" => "form[fields][#{index}][fields]" }
    = render_fields(field_set.fields, "form[fields][#{index}][fields]")
  
  = link_to "Delete", '#', :class => 'delete'
  

app/views/forms/forms/_select_field.haml
.select-field{ 'data-index' => index }
  %input{:type => "hidden", :name => "#{prefix}[type]", :value => select_field.type}
  
  .drag= image_tag "wheelhouse-forms/select.png", :alt => "Select Field", :title => "Select Field"
  
  %input{:type => "text", :name => "#{prefix}[label]", :title => "Select Field Label", :placeholder => "Select Field Label", :value => select_field.label}
  
  %label.required
    %input{:type => "checkbox", :name => "#{prefix}[required]", :value => "1", :checked => select_field.required?}
    This field is required
  
  = link_to "Delete", '#', :class => 'delete'
  
  %ul.options
    %li
      %label Options:
      
    - select_field.options(true).each do |option|
      %li
        %input{:type => "text", :name => "#{prefix}[options][]", :value => option}

app/views/forms/forms/_states_dropdown.haml
.states-dropdown{ 'data-index' => index }
  %input{:type => "hidden", :name => "#{prefix}[type]", :value => states_dropdown.type}
  
  .drag= image_tag "wheelhouse-forms/states.png", :alt => "States Dropdown", :title => "States Dropdown"
  
  %input{:type => "text", :name => "#{prefix}[label]", :title => "States Dropdown Label", :placeholder => "States Dropdown Label", :value => states_dropdown.label}
  
  %label.required
    %input{:type => "checkbox", :name => "#{prefix}[required]", :value => "1", :checked => states_dropdown.required?}
    This field is required
  
  %select{:name => "#{prefix}[country]"}
    %option{:value => "US"} US States
    %option{:value => "Australia"} Australian States
  
  = link_to "Delete", '#', :class => 'delete'

app/views/forms/forms/_submissions.haml
- @submissions = resource.submissions.paginate(:page => params[:p])

%h2 Latest Submissions

= table_for Forms::Submission do |table|
  - table.rows(@submissions) do |row, submission|
    - row.resource = [@form, submission]
  
    - if resource.first_content_field
      = row.column(resource.first_content_field.label) { submission.value_for(resource.first_content_field) }
    
    = row.column(:submitted_at) { submission.created_at.in_time_zone.to_s(:long) }
  
    = row.controls do |c|
      = c.delete
  
  - table.empty do
    No submissions have been posted.

= will_paginate @submissions

app/views/forms/forms/_text_field.haml
= basic_field(text_field, :index => index, :prefix => prefix, :id => id, :type => "text-field", :description => "Text Field")

app/views/forms/forms/designer.haml
- tab :fields do
  #fields{ "data-prefix" => "form[fields]" }
    = render_fields(@form.fields, "form[fields]")
  
  = field_template "field-set-template", Forms::Fields::FieldSet
  = field_template "text-field-template", Forms::Fields::TextField
  = field_template "text-area-template", Forms::Fields::TextArea
  = field_template "select-field-template", Forms::Fields::SelectField
  = field_template "checkbox-template", Forms::Fields::Checkbox
  = field_template "checkboxes-template", Forms::Fields::Checkboxes
  = field_template "radio-buttons-template", Forms::Fields::RadioButtons
  = field_template "states-dropdown-template", Forms::Fields::StatesDropdown
  = field_template "countries-dropdown-template", Forms::Fields::CountriesDropdown
  = field_template "content-field-template", Forms::Fields::ContentField
  = field_template "custom-field-template", Forms::Fields::CustomField if Forms::Plugin.config.wheelhouse.forms.custom_fields

- tab :content do
  = field :title do
    = form.text_field :title, :title => true
    = note "The form title will appear in the title bar of the user's browser window."
    
  = content

- tab :email do
  = field :recipients_string do
    = form.text_field :recipients_string
    = note "Separate email addresses with commas."
  
  = field :subject do
    = form.text_field :subject

- sidebar do
  = render "wheelhouse/admin/resource/default_sidebar"
  
  %ul#primary-tools.tools
    %li.text-field= link_to "Add Text Field", "#"
    %li.text-area= link_to "Add Text Area", "#"
    %li.select-field= link_to "Add Select Field", "#"
    %li.checkbox= link_to "Add Single Checkbox", "#"
    %li.checkboxes= link_to "Add Checkboxes", "#"
    %li.radio-buttons= link_to "Add Radio Buttons", "#"
    %li.field-set= link_to "Add Field Set", "#"
  
  %ul#extra-tools.tools
    %li.states-dropdown= link_to "Add States Dropdown", "#"
    %li.countries-dropdown= link_to "Add Countries Dropdown", "#"
    %li.content-field= link_to "Add Content Field", "#"
    %li.custom-field= link_to "Add Custom Field", "#" if Forms::Plugin.config.wheelhouse.forms.custom_fields

- content_for(:head) do
  = stylesheet_link_tag "wheelhouse-forms/admin"

- content_for(:javascript) do
  = javascript_include_tag "wheelhouse-forms/admin"

app/views/forms/forms/edit.html.haml
- title "Editing Form"
- breadcrumb @form.label, form_path(@form)
- breadcrumb "Editing Form"

= render_form "designer"

app/views/forms/forms/form.haml
- tab :submissions => "submissions"

- sidebar do
  .buttons
    = button "Form Designer", :icon => :publish, :url => edit_form_path(@form)
  
  /%p.export-csv
  /  = link_to "Export Results as CSV", "#"#, forms_form_submissions_path(@form, :format => :csv)
  
  %hr

  - if last_submission = @form.submissions.first
    %p.owner Last submission: #{timestamp(last_submission.created_at)}
  
  = owner
  
  %hr

- content_for(:head) do
  = stylesheet_link_tag "wheelhouse-forms/admin"

app/views/forms/forms/new.html.haml
- title "New Form"
- breadcrumb "New Form"

= render_form "designer"

app/views/forms/forms/show.html.haml
- title @form.label
- breadcrumb @form.label

= render_form